// The emitter core (BA-B5): SceneSpec → deterministic Blender Python. Composable
// sections written through PyWriter (doc 03): header → preamble (version gate,
// THIDE: helper) → scene reset → PLY import (+ runtime bounds) → baseline
// material/light (placeholder until BA-B7) → static auto-framed camera (placeholder
// until BA-B6) → engine + GPU cascade → render/output settings → progress hooks →
// render. Same spec (+ assets) ⇒ byte-identical script (NFR-03, golden-tested).
//
// Version adaptivity is RUNTIME probing inside the script (R-07): a bpy.app.version
// gate, the EEVEE engine id probed by assignment (BLENDER_EEVEE_NEXT vs
// BLENDER_EEVEE), and hasattr checks around the Cycles device-refresh API — never
// C#-side Blender-version branching.
//
// THIDE: protocol (D-08, tier 1 — parsed by the BA-B10 runner):
//   spec-hash=<sha256>  blender=<x.y.z>  phase=<scene|import|engine|render>
//   device=<OPTIX|CUDA|HIP|ONEAPI|METAL|CPU|EEVEE>  frames=<N>  frame=<n>/<N>
//   output=<path>  error=<message>  done=1

namespace Therion.Blender.Emit;

/// <summary>
/// Files embedded into a self-contained script (D-14). The caller (pipeline/service)
/// reads them from disk so the generator itself stays pure and testable.
/// </summary>
public sealed record ScriptAssets
{
    /// <summary>The scene-meta.json text to embed (required for self-contained mode).</summary>
    public string? SceneMetaJson { get; init; }

    /// <summary>The transport PLY bytes to embed base64 (required when the spec sets
    /// <see cref="SourceSpec.EmbedMesh"/>).</summary>
    public byte[]? PlyBytes { get; init; }
}

/// <summary>Compiles a validated <see cref="SceneSpec"/> into a Blender Python script.</summary>
public static class ScriptGenerator
{
    /// <summary>
    /// Generates the script. Throws <see cref="ArgumentException"/> when the spec fails
    /// validation (same error surface as the UI/CLI) or when self-contained assets are
    /// missing. Run with: <c>blender -b --factory-startup --python script.py</c>.
    /// </summary>
    public static string Generate(SceneSpec spec, ScriptAssets? assets = null)
    {
        ArgumentNullException.ThrowIfNull(spec);
        var errors = SceneSpecValidator.Validate(spec);
        if (errors.Count > 0)
            throw new ArgumentException(
                "The render spec is invalid: " + string.Join("; ", errors.Select(e => $"{e.Path}: {e.Message}")),
                nameof(spec));
        if (spec.Source.SelfContained && assets?.SceneMetaJson is null)
            throw new ArgumentException("Self-contained mode needs ScriptAssets.SceneMetaJson.", nameof(assets));
        if (spec.Source is { SelfContained: true, EmbedMesh: true } && assets?.PlyBytes is null)
            throw new ArgumentException("EmbedMesh needs ScriptAssets.PlyBytes.", nameof(assets));

        var w = new PyWriter();
        EmitHeader(w, spec);
        EmitPreamble(w, spec);
        EmitEmbeddedAssets(w, spec, assets);
        EmitSceneReset(w, spec);
        EmitImport(w, spec);
        EmitBaselineLookdev(w);
        EmitCamera(w, spec);
        EmitEngine(w, spec);
        EmitOutput(w, spec);
        EmitProgressHooks(w, spec);
        EmitRender(w, spec);
        return w.ToString();
    }

    private static void EmitHeader(PyWriter w, SceneSpec spec)
    {
        w.Line("# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.");
        if (!string.IsNullOrWhiteSpace(spec.Name))
            w.Line($"# Spec: {spec.Name.ReplaceLineEndings(" ")}");
        if (!string.IsNullOrWhiteSpace(spec.CreatedBy))
            w.Line($"# Created by: {spec.CreatedBy.ReplaceLineEndings(" ")}");
        w.Line("# Run: blender -b --factory-startup --python <this file>");
        w.Blank();
    }

    private static void EmitPreamble(PyWriter w, SceneSpec spec)
    {
        w.Line("import math");
        w.Line("import os");
        w.Line("import sys");
        if (spec.Source is { SelfContained: true })
        {
            if (spec.Source.EmbedMesh) w.Line("import base64");
            w.Line("import tempfile");
        }
        w.Blank();
        w.Line("import bpy");
        w.Line("import mathutils");
        w.Blank();
        w.Line($"SPEC_HASH = {PyWriter.Str(SceneSpecSerializer.ComputeHash(spec))}");
        w.Blank();
        w.Blank();
        using (w.Block("def thide(key, value):"))
            w.Line("print(\"THIDE:\" + key + \"=\" + str(value), flush=True)");
        w.Blank();
        w.Blank();
        using (w.Block("def fail(message, code=64):"))
        {
            w.Line("thide(\"error\", message)");
            w.Line("sys.exit(code)");
        }
        w.Blank();
        w.Blank();
        w.Line("thide(\"spec-hash\", SPEC_HASH)");
        w.Line("thide(\"blender\", \".\".join(str(v) for v in bpy.app.version))");
        using (w.Block("if bpy.app.version < (4, 2, 0):"))
            w.Line("fail(\"ThIDE requires Blender 4.2 or newer, found \" + bpy.app.version_string)");
        w.Blank();
    }

    private static void EmitEmbeddedAssets(PyWriter w, SceneSpec spec, ScriptAssets? assets)
    {
        if (!spec.Source.SelfContained) return;

        w.Line("# ---- embedded assets (self-contained mode, D-14) ----");
        // The meta JSON travels as a plain (escaped) string constant; label/overlay
        // sections of later batches parse it at runtime with json.loads.
        w.Line($"SCENE_META_JSON = {PyWriter.Str(assets!.SceneMetaJson!)}");
        if (spec.Source.EmbedMesh)
        {
            w.Line($"PLY_BASE64 = {PyWriter.Str(Convert.ToBase64String(assets.PlyBytes!))}");
        }
        w.Blank();
    }

    private static void EmitSceneReset(PyWriter w, SceneSpec spec)
    {
        w.Line("# ---- scene reset ----");
        w.Line("thide(\"phase\", \"scene\")");
        w.Line("bpy.ops.wm.read_factory_settings(use_empty=True)");
        w.Line("scene = bpy.context.scene");
        w.Line("scene.unit_settings.system = 'METRIC'");
        w.Line("scene.unit_settings.scale_length = 1.0");
        w.Line($"SEED = {PyWriter.Num(spec.Seed)}");
        w.Blank();
    }

    private static void EmitImport(PyWriter w, SceneSpec spec)
    {
        w.Line("# ---- import model ----");
        w.Line("thide(\"phase\", \"import\")");
        if (spec.Source is { SelfContained: true, EmbedMesh: true })
        {
            w.Line("_ply_file = tempfile.NamedTemporaryFile(suffix=\".ply\", delete=False)");
            w.Line("_ply_file.write(base64.b64decode(PLY_BASE64))");
            w.Line("_ply_file.close()");
            w.Line("PLY_PATH = _ply_file.name");
        }
        else
        {
            w.Line($"PLY_PATH = {PyWriter.Str(spec.Source.PlyPath)}");
        }
        using (w.Block("if not os.path.exists(PLY_PATH):"))
            w.Line("fail(\"model file not found: \" + PLY_PATH)");
        w.Line("bpy.ops.wm.ply_import(filepath=PLY_PATH)");
        w.Line("model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None");
        using (w.Block("if model is None:"))
            w.Line("fail(\"PLY import produced no object\")");
        w.Line("model.name = \"CaveModel\"");
        w.Line("thide(\"triangles\", len(model.data.polygons))");
        w.Blank();
        w.Line("# Runtime bounds of the (already recentered) model drive framing and clipping.");
        w.Line("_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]");
        w.Line("bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))");
        w.Line("bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))");
        w.Line("bounds_center = (bounds_min + bounds_max) / 2");
        w.Line("bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)");
        w.Blank();
    }

    private static void EmitBaselineLookdev(PyWriter w)
    {
        w.Line("# ---- baseline material + light (replaced by the BA-B7 sections) ----");
        w.Line("mat = bpy.data.materials.new(\"CaveRock\")");
        w.Line("mat.use_nodes = True");
        w.Line("_bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')");
        w.Line("_bsdf.inputs[\"Roughness\"].default_value = 0.9");
        using (w.Block("if model.data.color_attributes:"))
        {
            // The converter writes depth-tint vertex colours; use them when present.
            w.Line("_vc = mat.node_tree.nodes.new(\"ShaderNodeVertexColor\")");
            w.Line("_vc.layer_name = model.data.color_attributes[0].name");
            w.Line("mat.node_tree.links.new(_vc.outputs[\"Color\"], _bsdf.inputs[\"Base Color\"])");
        }
        w.Line("model.data.materials.append(mat)");
        w.Blank();
        w.Line("_sun = bpy.data.lights.new(\"Sun\", type='SUN')");
        w.Line("_sun.energy = 3.0");
        w.Line("sun = bpy.data.objects.new(\"Sun\", _sun)");
        w.Line("scene.collection.objects.link(sun)");
        w.Line("sun.rotation_euler = (0.9, 0.2, 0.6)");
        w.Blank();
    }

    private static void EmitCamera(PyWriter w, SceneSpec spec)
    {
        w.Line("# ---- camera: static auto-framed (replaced by the BA-B6 camera engine) ----");
        w.Line("cam_data = bpy.data.cameras.new(\"Camera\")");
        w.Line($"cam_data.lens = {PyWriter.Num(spec.Camera.FocalLength)}");
        w.Line("cam_data.clip_start = max(0.01, bounds_radius / 1000.0)");
        w.Line("cam_data.clip_end = max(100.0, bounds_radius * 10.0)");
        w.Line("cam = bpy.data.objects.new(\"Camera\", cam_data)");
        w.Line("scene.collection.objects.link(cam)");
        w.Line("scene.camera = cam");
        w.Blank();
        w.Line("# Back the camera off along an iso direction until the bounding sphere fits the FOV.");
        w.Line($"_padding = {PyWriter.Num(spec.Camera.AutoFramePadding)}");
        w.Line("_distance = (bounds_radius * _padding) / math.tan(cam_data.angle / 2.0) + bounds_radius");
        w.Line("_direction = mathutils.Vector((1.0, -1.0, 0.7)).normalized()");
        w.Line("cam.location = bounds_center + _direction * _distance");
        w.Line("cam.rotation_euler = (bounds_center - cam.location).to_track_quat('-Z', 'Y').to_euler()");
        w.Blank();
    }

    private static void EmitEngine(PyWriter w, SceneSpec spec)
    {
        w.Line("# ---- engine ----");
        w.Line("thide(\"phase\", \"engine\")");
        w.Line($"scene.render.film_transparent = {PyWriter.Bool(spec.Engine.TransparentBackground)}");
        if (spec.Engine.Kind == RenderEngineKind.Eevee)
        {
            EmitEevee(w, spec);
            return;
        }

        w.Line("scene.render.engine = 'CYCLES'");
        w.Line($"scene.cycles.samples = {PyWriter.Num(spec.Engine.Samples)}");
        w.Line($"scene.cycles.use_denoising = {PyWriter.Bool(spec.Engine.Denoise)}");
        w.Line("scene.cycles.seed = SEED");
        w.Blank();

        if (spec.Engine.Gpu == GpuMode.CpuOnly)
        {
            w.Line("scene.cycles.device = 'CPU'");
            w.Line("thide(\"device\", \"CPU\")");
            w.Blank();
            return;
        }

        // GPU cascade (doc 03; mirrors blender-cli-rendering/BlenderProc practice):
        // try each backend, enable its devices, fall back to CPU when none works.
        using (w.Block("def _enable_gpu(kind):"))
        {
            w.Line("prefs = bpy.context.preferences.addons[\"cycles\"].preferences");
            w.Line("prefs.compute_device_type = kind");
            // The device-refresh API has moved between versions — probe it (R-07).
            using (w.Block("if hasattr(prefs, \"refresh_devices\"):"))
                w.Line("prefs.refresh_devices()");
            using (w.Block("else:"))
                w.Line("prefs.get_devices()");
            w.Line("found = False");
            using (w.Block("for device in prefs.devices:"))
            {
                w.Line("device.use = device.type == kind");
                w.Line("found = found or device.use");
            }
            w.Line("return found");
        }
        w.Blank();
        var cascade = spec.Engine.Gpu == GpuMode.Auto
            ? new[] { "OPTIX", "CUDA", "HIP", "ONEAPI", "METAL" }
            : [CyclesDeviceType(spec.Engine.Gpu)];
        w.Line($"_gpu_cascade = [{string.Join(", ", cascade.Select(PyWriter.Str))}]");
        using (w.Block("for _kind in _gpu_cascade:"))
        {
            using (w.Block("try:"))
            {
                using (w.Block("if _enable_gpu(_kind):"))
                {
                    w.Line("scene.cycles.device = 'GPU'");
                    w.Line("thide(\"device\", _kind)");
                    w.Line("break");
                }
            }
            using (w.Block("except Exception:"))
                w.Line("continue");
        }
        using (w.Block("else:"))
        {
            w.Line("scene.cycles.device = 'CPU'");
            w.Line("thide(\"device\", \"CPU\")");
        }
        w.Blank();
    }

    private static void EmitEevee(PyWriter w, SceneSpec spec)
    {
        // EEVEE was renamed BLENDER_EEVEE_NEXT in 4.2; probe by assignment so a future
        // rename-back keeps working (R-04/R-07). Device config does not apply (D-09).
        using (w.Block("for _engine_id in (\"BLENDER_EEVEE_NEXT\", \"BLENDER_EEVEE\"):"))
        {
            using (w.Block("try:"))
            {
                w.Line("scene.render.engine = _engine_id");
                w.Line("break");
            }
            using (w.Block("except TypeError:"))
                w.Line("continue");
        }
        using (w.Block("else:"))
            w.Line("fail(\"no EEVEE engine is available in this Blender\")");
        w.Line($"scene.eevee.taa_render_samples = {PyWriter.Num(spec.Engine.Samples)}");
        w.Line("thide(\"device\", \"EEVEE\")");
        w.Blank();
    }

    private static string CyclesDeviceType(GpuMode mode) => mode switch
    {
        GpuMode.OptiX => "OPTIX",
        GpuMode.Cuda => "CUDA",
        GpuMode.Hip => "HIP",
        GpuMode.OneApi => "ONEAPI",
        GpuMode.Metal => "METAL",
        _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, "Not a specific GPU backend."),
    };

    private static void EmitOutput(PyWriter w, SceneSpec spec)
    {
        int frames = SceneSpecValidator.FrameCount(spec);
        w.Line("# ---- output ----");
        w.Line($"scene.render.resolution_x = {PyWriter.Num(spec.Output.Width)}");
        w.Line($"scene.render.resolution_y = {PyWriter.Num(spec.Output.Height)}");
        w.Line("scene.render.resolution_percentage = 100");
        w.Line($"scene.render.fps = {PyWriter.Num(spec.Animation.Fps)}");
        w.Line("scene.frame_start = 1");
        w.Line($"scene.frame_end = {PyWriter.Num(frames)}");
        w.Line($"OUT_DIR = {PyWriter.Str(spec.Output.OutputDirectory)}");
        w.Line("os.makedirs(OUT_DIR, exist_ok=True)");

        switch (spec.Output.Kind)
        {
            case OutputKind.Video:
                w.Line("scene.render.image_settings.file_format = 'FFMPEG'");
                w.Line($"scene.render.ffmpeg.format = {PyWriter.Str(FfmpegContainer(spec.Output.Container))}");
                w.Line($"scene.render.ffmpeg.codec = {PyWriter.Str(spec.Output.Container == VideoContainer.WebM ? "WEBM" : "H264")}");
                w.Line("scene.render.ffmpeg.constant_rate_factor = 'HIGH'");
                w.Line("scene.render.ffmpeg.audio_codec = 'NONE'");
                w.Line($"scene.render.filepath = os.path.join(OUT_DIR, {PyWriter.Str(spec.Output.BaseName + ContainerExtension(spec.Output.Container))})");
                break;
            case OutputKind.FrameSequence:
                w.Line("scene.render.image_settings.file_format = 'PNG'");
                w.Line($"scene.render.image_settings.color_mode = {PyWriter.Str(spec.Engine.TransparentBackground ? "RGBA" : "RGB")}");
                w.Line($"scene.render.filepath = os.path.join(OUT_DIR, {PyWriter.Str(spec.Output.BaseName + "_####")})");
                break;
            case OutputKind.Still:
                w.Line("scene.render.image_settings.file_format = 'PNG'");
                w.Line($"scene.render.image_settings.color_mode = {PyWriter.Str(spec.Engine.TransparentBackground ? "RGBA" : "RGB")}");
                w.Line($"scene.render.filepath = os.path.join(OUT_DIR, {PyWriter.Str(spec.Output.BaseName + ".png")})");
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(spec), spec.Output.Kind, "Unknown output kind.");
        }
        w.Blank();
    }

    private static string FfmpegContainer(VideoContainer container) => container switch
    {
        VideoContainer.Mp4 => "MPEG4",
        VideoContainer.Mkv => "MKV",
        VideoContainer.WebM => "WEBM",
        _ => throw new ArgumentOutOfRangeException(nameof(container), container, "Unknown container."),
    };

    private static string ContainerExtension(VideoContainer container) => container switch
    {
        VideoContainer.Mp4 => ".mp4",
        VideoContainer.Mkv => ".mkv",
        VideoContainer.WebM => ".webm",
        _ => throw new ArgumentOutOfRangeException(nameof(container), container, "Unknown container."),
    };

    private static void EmitProgressHooks(PyWriter w, SceneSpec spec)
    {
        int frames = SceneSpecValidator.FrameCount(spec);
        w.Line("# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----");
        w.Line($"FRAME_COUNT = {PyWriter.Num(frames)}");
        w.Blank();
        w.Blank();
        // Handler signatures differ across versions — accept anything (R-07).
        using (w.Block("def _thide_frame_written(*args):"))
            w.Line("thide(\"frame\", str(bpy.context.scene.frame_current) + \"/\" + str(FRAME_COUNT))");
        w.Blank();
        w.Blank();
        using (w.Block("def _thide_render_cancelled(*args):"))
            w.Line("thide(\"render-cancel\", \"1\")");
        w.Blank();
        w.Blank();
        w.Line("bpy.app.handlers.render_write.append(_thide_frame_written)");
        w.Line("bpy.app.handlers.render_cancel.append(_thide_render_cancelled)");
        w.Blank();
    }

    private static void EmitRender(PyWriter w, SceneSpec spec)
    {
        w.Line("# ---- render ----");
        w.Line("thide(\"phase\", \"render\")");
        w.Line("thide(\"frames\", FRAME_COUNT)");
        if (spec.Output.Kind == OutputKind.Still)
            w.Line("bpy.ops.render.render(write_still=True)");
        else
            w.Line("bpy.ops.render.render(animation=True)");
        w.Line("thide(\"output\", scene.render.filepath)");
        w.Line("thide(\"done\", \"1\")");
    }
}
