# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden camera
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "812186f0f5dc6c54363dfb120c485b8e0eda39f2689ab3ec4f64ec0d7b116ca9"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 5

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- baseline material + light (replaced by the BA-B7 sections) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
if model.data.color_attributes:
    _vc = mat.node_tree.nodes.new("ShaderNodeVertexColor")
    _vc.layer_name = model.data.color_attributes[0].name
    mat.node_tree.links.new(_vc.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0
sun = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(sun)
sun.rotation_euler = (0.9, 0.2, 0.6)

# ---- camera: flythrough (BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 35
cam_data.sensor_fit = 'HORIZONTAL'
cam_data.sensor_width = 36
cam_data.clip_start = 0.01
cam_data.clip_end = 670.8203932499368
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

cam_target = bpy.data.objects.new("CameraTarget", None)
scene.collection.objects.link(cam_target)
_track = cam.constraints.new(type='TRACK_TO')
_track.target = cam_target
_track.track_axis = 'TRACK_NEGATIVE_Z'
_track.up_axis = 'UP_Y'

# CAM_KEYS: (frame, cam_x, cam_y, cam_z, tgt_x, tgt_y, tgt_z)
CAM_KEYS = [
    (1, -30, -20, -10, -26.05023747233318, -17.037678104249885, -9.210047494466636),
    (2, -20.088411460772463, -12.566308595579347, -8.017682292154493, -16.138648933105642, -9.603986699829232, -7.227729786621129),
    (3, -9.895310613173137, -5.559569133233211, -5.979062122634628, -5.715013989702388, -2.9468837435639923, -5.143002797940477),
    (4, 0.8918451577096462, 0.4459225788548231, -3.821630968458071, 5.286861753651655, 2.66392100208666, -2.950823699374002),
    (5, 11.768153107562693, 6.3675160614643955, -1.8397451815606813, 15.97643650344415, 8.9842910022961, -1.2031417995407798),
    (6, 22.134831493352134, 13.237359577793445, -0.29353931821783563, 25.91567668233766, 16.38806390194805, 0.5886578925454544),
    (7, 31.364514919736916, 21.364514919736916, 2.1215049732456386, 34.805750927795344, 24.80575092779534, 3.268583642598447),
    (8, 40, 30, 5, 43.441236008058425, 33.441236008058425, 6.147078669352808),
]
for _k in CAM_KEYS:
    cam.location = (_k[1], _k[2], _k[3])
    cam.keyframe_insert(data_path="location", frame=_k[0])
    cam_target.location = (_k[4], _k[5], _k[6])
    cam_target.keyframe_insert(data_path="location", frame=_k[0])

def _thide_set_interp(idblock, mode):
    _ad = getattr(idblock, "animation_data", None)
    if not _ad or not _ad.action:
        return
    _curves = getattr(_ad.action, "fcurves", None)
    if not _curves:
        try:
            _slot = _ad.action_slot
            _curves = []
            for _layer in _ad.action.layers:
                for _strip in _layer.strips:
                    _bag = _strip.channelbag(_slot)
                    if _bag:
                        _curves = list(_bag.fcurves) + _curves
        except Exception:
            _curves = []
    for _fc in _curves:
        for _kp in _fc.keyframe_points:
            _kp.interpolation = "LINEAR"
_thide_set_interp(cam, "LINEAR")
_thide_set_interp(cam_target, "LINEAR")

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 32
scene.cycles.use_denoising = True
scene.cycles.seed = SEED

scene.cycles.device = 'CPU'
thide("device", "CPU")

# ---- output ----
scene.render.resolution_x = 960
scene.render.resolution_y = 540
scene.render.resolution_percentage = 100
scene.render.fps = 8
scene.frame_start = 1
scene.frame_end = 8
OUT_DIR = "out"
os.makedirs(OUT_DIR, exist_ok=True)
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = "MPEG4"
scene.render.ffmpeg.codec = "H264"
scene.render.ffmpeg.constant_rate_factor = 'HIGH'
scene.render.ffmpeg.audio_codec = 'NONE'
scene.render.filepath = os.path.join(OUT_DIR, "golden-camera.mp4")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 8


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(animation=True)
thide("output", scene.render.filepath)
thide("done", "1")
