# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden camera
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "f5171cbfc57aab797ddcd5262f2d61a51f3d5bfe0ec0b53c7c4e73e13c676dd5"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 5

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- baseline material + light (replaced by the BA-B7 sections) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
if model.data.color_attributes:
    _vc = mat.node_tree.nodes.new("ShaderNodeVertexColor")
    _vc.layer_name = model.data.color_attributes[0].name
    mat.node_tree.links.new(_vc.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0
sun = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(sun)
sun.rotation_euler = (0.9, 0.2, 0.6)

# ---- camera: helix (BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 35
cam_data.sensor_fit = 'HORIZONTAL'
cam_data.sensor_width = 36
cam_data.clip_start = 0.06708203932499368
cam_data.clip_end = 670.8203932499368
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

cam_target = bpy.data.objects.new("CameraTarget", None)
scene.collection.objects.link(cam_target)
_track = cam.constraints.new(type='TRACK_TO')
_track.target = cam_target
_track.track_axis = 'TRACK_NEGATIVE_Z'
_track.up_axis = 'UP_Y'

# CAM_KEYS: (frame, cam_x, cam_y, cam_z, tgt_x, tgt_y, tgt_z)
CAM_KEYS = [
    (1, 217.94054357894623, 65.71750072566732, 19.166666666666664, 10, 10, 19.166666666666664),
    (2, 159.6646723851566, 159.6646723851566, 17.5, 10, 10, 17.5),
    (3, 63.844643558418, 210.95094547545227, 15.833333333333336, 10, 10, 15.833333333333336),
    (4, -42.90821497479336, 207.45614642370526, 14.166666666666664, 10, 10, 14.166666666666664),
    (5, -131.98956098078958, 151.9895609807896, 12.5, 10, 10, 12.5),
    (6, -180.46654832021125, 61.03535780754407, 10.833333333333336, 10, 10, 10.833333333333336),
    (7, -176.9717492684643, -40.09892922391928, 9.166666666666671, 10, 10, 9.166666666666671),
    (8, -124.31444957642262, -124.31444957642256, 7.5, 10, 10, 7.5),
    (9, -38.226072056670006, -169.98215116497028, 5.833333333333329, 10, 10, 5.833333333333329),
    (10, 57.28964347304529, -166.4873521132233, 4.166666666666671, 10, 10, 4.166666666666671),
    (11, 136.63933817205555, -116.63933817205559, 2.5, 10, 10, 2.5),
    (12, 179.49775400972928, -35.41678630579604, 0.8333333333333286, 10, 10, 0.8333333333333286),
    (13, 157.2675021677689, 95.024932019445, -1.6666666666666643, 10, 10, -1.6666666666666643),
    (14, 93.21589091264838, 154.13415105781633, -3.3333333333333357, 10, 10, -3.3333333333333357),
    (15, 10.00000000000005, 172.81369961170344, -5, 10, 10, -5),
    (16, -69.5978086990549, 147.86744883791133, -6.666666666666664, 10, 10, -6.666666666666664),
    (17, -124.73409772795873, 87.78876759225827, -8.333333333333336, 10, 10, -8.333333333333336),
    (18, -141.9594529709232, 10.000000000000055, -10, 10, 10, -10),
    (19, -118.46739550805373, -64.17068537866477, -11.666666666666664, 10, 10, -11.666666666666664),
    (20, -62.36164427186816, -115.33404439810113, -13.333333333333336, 10, 10, -13.333333333333336),
    (21, 9.99999999999994, -131.10520633014298, -15, 10, 10, -15),
    (22, 78.74356205827466, -109.06734217819616, -16.666666666666664, 10, 10, -16.666666666666664),
    (23, 125.93399106824354, -56.93452095147806, -18.333333333333336, 10, 10, -18.333333333333336),
    (24, 140.25095968936276, 9.999999999999936, -20, 10, 10, -20),
]
for _k in CAM_KEYS:
    cam.location = (_k[1], _k[2], _k[3])
    cam.keyframe_insert(data_path="location", frame=_k[0])
    cam_target.location = (_k[4], _k[5], _k[6])
    cam_target.keyframe_insert(data_path="location", frame=_k[0])

def _thide_set_interp(idblock, mode):
    _ad = getattr(idblock, "animation_data", None)
    if not _ad or not _ad.action:
        return
    _curves = getattr(_ad.action, "fcurves", None)
    if not _curves:
        try:
            _slot = _ad.action_slot
            _curves = []
            for _layer in _ad.action.layers:
                for _strip in _layer.strips:
                    _bag = _strip.channelbag(_slot)
                    if _bag:
                        _curves = list(_bag.fcurves) + _curves
        except Exception:
            _curves = []
    for _fc in _curves:
        for _kp in _fc.keyframe_points:
            _kp.interpolation = "LINEAR"
_thide_set_interp(cam, "LINEAR")
_thide_set_interp(cam_target, "LINEAR")

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 32
scene.cycles.use_denoising = True
scene.cycles.seed = SEED

scene.cycles.device = 'CPU'
thide("device", "CPU")

# ---- output ----
scene.render.resolution_x = 960
scene.render.resolution_y = 540
scene.render.resolution_percentage = 100
scene.render.fps = 8
scene.frame_start = 1
scene.frame_end = 24
OUT_DIR = "out"
os.makedirs(OUT_DIR, exist_ok=True)
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = "MPEG4"
scene.render.ffmpeg.codec = "H264"
scene.render.ffmpeg.constant_rate_factor = 'HIGH'
scene.render.ffmpeg.audio_codec = 'NONE'
scene.render.filepath = os.path.join(OUT_DIR, "golden-camera.mp4")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 24


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(animation=True)
thide("output", scene.render.filepath)
thide("done", "1")
