# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden camera
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "8391a5f50eed6263f750ee52bcfacffdd524a981e5c1cff924256dee90791edd"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


def thide_enum(obj, prop, candidates):
    for candidate in candidates:
        try:
            setattr(obj, prop, candidate)
            return candidate
        except TypeError:
            continue
    return None


def thide_fcurves(idblock):
    _ad = getattr(idblock, "animation_data", None)
    if not _ad or not _ad.action:
        return []
    _curves = getattr(_ad.action, "fcurves", None)
    if _curves:
        return list(_curves)
    _curves = []
    try:
        for _layer in _ad.action.layers:
            for _strip in _layer.strips:
                _bag = _strip.channelbag(_ad.action_slot)
                if _bag:
                    _curves = list(_bag.fcurves) + _curves
    except Exception:
        return []
    return _curves


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 5

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- material: depthgradient (BA-B7) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_nt = mat.node_tree
_bsdf = next(n for n in _nt.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
_geo = _nt.nodes.new("ShaderNodeNewGeometry")
_sep = _nt.nodes.new("ShaderNodeSeparateXYZ")
_nt.links.new(_geo.outputs["Position"], _sep.inputs["Vector"])
_map = _nt.nodes.new("ShaderNodeMapRange")
_map.inputs["From Min"].default_value = bounds_min.z
_map.inputs["From Max"].default_value = bounds_max.z
_nt.links.new(_sep.outputs["Z"], _map.inputs["Value"])
_ramp = _nt.nodes.new("ShaderNodeValToRGB")
_cr = _ramp.color_ramp
_cr.elements[0].position = 0.0
_cr.elements[0].color = (0.018500220128379697, 0.03560131487502034, 0.13286832155381798, 1.0)
_cr.elements[1].position = 1.0
_cr.elements[1].color = (0.8879231178819663, 0.7454042095403874, 0.43415363617474895, 1.0)
_e = _cr.elements.new(0.25)
_e.color = (0.10702310297826761, 0.1559264637078274, 0.3419144249086609, 1.0)
_e = _cr.elements.new(0.5)
_e.color = (0.39157247774972326, 0.1559264637078274, 0.10224173308810132, 1.0)
_e = _cr.elements.new(0.75)
_e.color = (0.6938717612919899, 0.39157247774972326, 0.14995978981060856, 1.0)
_nt.links.new(_map.outputs["Result"], _ramp.inputs["Fac"])
_nt.links.new(_ramp.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

# ---- camera: helix (BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 35
cam_data.sensor_fit = 'HORIZONTAL'
cam_data.sensor_width = 36
cam_data.clip_start = 0.06708203932499368
cam_data.clip_end = 670.8203932499368
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

cam_target = bpy.data.objects.new("CameraTarget", None)
scene.collection.objects.link(cam_target)
_track = cam.constraints.new(type='TRACK_TO')
_track.target = cam_target
_track.track_axis = 'TRACK_NEGATIVE_Z'
_track.up_axis = 'UP_Y'

# CAM_KEYS: (frame, cam_x, cam_y, cam_z, tgt_x, tgt_y, tgt_z)
CAM_KEYS = [
    (1, 217.94054357894623, 65.71750072566732, 19.166666666666664, 10, 10, 19.166666666666664),
    (2, 159.6646723851566, 159.6646723851566, 17.5, 10, 10, 17.5),
    (3, 63.844643558418, 210.95094547545227, 15.833333333333336, 10, 10, 15.833333333333336),
    (4, -42.90821497479336, 207.45614642370526, 14.166666666666664, 10, 10, 14.166666666666664),
    (5, -131.98956098078958, 151.9895609807896, 12.5, 10, 10, 12.5),
    (6, -180.46654832021125, 61.03535780754407, 10.833333333333336, 10, 10, 10.833333333333336),
    (7, -176.9717492684643, -40.09892922391928, 9.166666666666671, 10, 10, 9.166666666666671),
    (8, -124.31444957642262, -124.31444957642256, 7.5, 10, 10, 7.5),
    (9, -38.226072056670006, -169.98215116497028, 5.833333333333329, 10, 10, 5.833333333333329),
    (10, 57.28964347304529, -166.4873521132233, 4.166666666666671, 10, 10, 4.166666666666671),
    (11, 136.63933817205555, -116.63933817205559, 2.5, 10, 10, 2.5),
    (12, 179.49775400972928, -35.41678630579604, 0.8333333333333286, 10, 10, 0.8333333333333286),
    (13, 157.2675021677689, 95.024932019445, -1.6666666666666643, 10, 10, -1.6666666666666643),
    (14, 93.21589091264838, 154.13415105781633, -3.3333333333333357, 10, 10, -3.3333333333333357),
    (15, 10.00000000000005, 172.81369961170344, -5, 10, 10, -5),
    (16, -69.5978086990549, 147.86744883791133, -6.666666666666664, 10, 10, -6.666666666666664),
    (17, -124.73409772795873, 87.78876759225827, -8.333333333333336, 10, 10, -8.333333333333336),
    (18, -141.9594529709232, 10.000000000000055, -10, 10, 10, -10),
    (19, -118.46739550805373, -64.17068537866477, -11.666666666666664, 10, 10, -11.666666666666664),
    (20, -62.36164427186816, -115.33404439810113, -13.333333333333336, 10, 10, -13.333333333333336),
    (21, 9.99999999999994, -131.10520633014298, -15, 10, 10, -15),
    (22, 78.74356205827466, -109.06734217819616, -16.666666666666664, 10, 10, -16.666666666666664),
    (23, 125.93399106824354, -56.93452095147806, -18.333333333333336, 10, 10, -18.333333333333336),
    (24, 140.25095968936276, 9.999999999999936, -20, 10, 10, -20),
]
for _k in CAM_KEYS:
    cam.location = (_k[1], _k[2], _k[3])
    cam.keyframe_insert(data_path="location", frame=_k[0])
    cam_target.location = (_k[4], _k[5], _k[6])
    cam_target.keyframe_insert(data_path="location", frame=_k[0])

def _thide_set_interp(idblock, mode):
    for _fc in thide_fcurves(idblock):
        for _kp in _fc.keyframe_points:
            _kp.interpolation = mode
_thide_set_interp(cam, "LINEAR")
_thide_set_interp(cam_target, "LINEAR")

# ---- lighting: sunsky (BA-B7) ----
_light_strength = 1
_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0 * _light_strength
_suno = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(_suno)
_suno.rotation_euler = (0.9, 0.2, 0.6)
world = bpy.data.worlds.new("CaveWorld")
scene.world = world
world.use_nodes = True
_wnt = world.node_tree
_bg = next(n for n in _wnt.nodes if n.type == 'BACKGROUND')
_sky = _wnt.nodes.new("ShaderNodeTexSky")
# 4.x names the physical sky NISHITA; 5.x replaced it with the *_SCATTERING models.
thide_enum(_sky, "sky_type", ("NISHITA", "MULTIPLE_SCATTERING", "SINGLE_SCATTERING"))
_wnt.links.new(_sky.outputs["Color"], _bg.inputs["Color"])
_bg.inputs["Strength"].default_value = 0.5 * _light_strength

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 32
scene.cycles.use_denoising = True
scene.cycles.seed = SEED
scene.cycles.max_bounces = 8
scene.cycles.diffuse_bounces = 3
scene.cycles.glossy_bounces = 3
scene.cycles.transmission_bounces = 4
scene.cycles.caustics_reflective = False
scene.cycles.caustics_refractive = False

scene.cycles.device = 'CPU'
thide("device", "CPU")

# ---- output ----
scene.render.resolution_x = 960
scene.render.resolution_y = 540
scene.render.resolution_percentage = 100
scene.render.fps = 8
scene.frame_start = 1
scene.frame_end = 24
OUT_DIR = "out"
os.makedirs(OUT_DIR, exist_ok=True)
_img = scene.render.image_settings
if hasattr(_img, "media_type"):
    thide_enum(_img, "media_type", ("VIDEO",))
if thide_enum(_img, "file_format", ("FFMPEG",)) is not None:
    scene.render.ffmpeg.format = "MPEG4"
    scene.render.ffmpeg.codec = "H264"
    scene.render.ffmpeg.constant_rate_factor = 'HIGH'
    scene.render.ffmpeg.audio_codec = 'NONE'
    scene.render.filepath = os.path.join(OUT_DIR, "golden-camera.mp4")
else:
    thide("warning", "This Blender build has no FFMPEG video encoder; rendering a PNG frame sequence instead of golden-camera.mp4.")
    if hasattr(_img, "media_type"):
        thide_enum(_img, "media_type", ("IMAGE",))
    _img.file_format = 'PNG'
    _img.color_mode = "RGB"
    scene.render.filepath = os.path.join(OUT_DIR, "golden-camera_####")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 24


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(animation=True)
thide("output", scene.render.filepath)
thide("done", "1")
