# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden camera
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "53236556808a4861274c41cba89157dee8ef586b7ca1dcec74846e6492f3afb8"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 5

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- baseline material + light (replaced by the BA-B7 sections) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
if model.data.color_attributes:
    _vc = mat.node_tree.nodes.new("ShaderNodeVertexColor")
    _vc.layer_name = model.data.color_attributes[0].name
    mat.node_tree.links.new(_vc.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0
sun = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(sun)
sun.rotation_euler = (0.9, 0.2, 0.6)

# ---- camera: orbit (BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 35
cam_data.sensor_fit = 'HORIZONTAL'
cam_data.sensor_width = 36
cam_data.clip_start = 0.06708203932499368
cam_data.clip_end = 670.8203932499368
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

cam_target = bpy.data.objects.new("CameraTarget", None)
scene.collection.objects.link(cam_target)
_track = cam.constraints.new(type='TRACK_TO')
_track.target = cam_target
_track.track_axis = 'TRACK_NEGATIVE_Z'
_track.up_axis = 'UP_Y'

# CAM_KEYS: (frame, cam_x, cam_y, cam_z, tgt_x, tgt_y, tgt_z)
CAM_KEYS = [
    (1, 220.12165780322232, 10, 76.47802901504163, 10, 10, 0),
    (2, 191.97069354289127, 115.06082890161115, 76.47802901504163, 10, 10, 0),
    (3, 115.06082890161117, 191.97069354289124, 76.47802901504163, 10, 10, 0),
    (4, 64.38348682798863, 212.96193593480638, 76.47802901504163, 10, 10, 0),
    (5, -44.38348682798865, 212.96193593480638, 76.47802901504163, 10, 10, 0),
    (6, -95.0608289016111, 191.97069354289127, 76.47802901504163, 10, 10, 0),
    (7, -171.97069354289127, 115.06082890161115, 76.47802901504163, 10, 10, 0),
    (8, -192.96193593480635, 64.38348682798868, 76.47802901504163, 10, 10, 0),
    (9, -192.96193593480638, -44.38348682798854, 76.47802901504163, 10, 10, 0),
    (10, -138.57844910681777, -138.57844910681771, 76.47802901504163, 10, 10, 0),
    (11, -95.06082890161126, -171.9706935428912, 76.47802901504163, 10, 10, 0),
    (12, 9.999999999999961, -200.12165780322232, 76.47802901504163, 10, 10, 0),
    (13, 115.06082890161117, -171.97069354289124, 76.47802901504163, 10, 10, 0),
    (14, 158.5784491068177, -138.57844910681777, 76.47802901504163, 10, 10, 0),
    (15, 212.96193593480638, -44.38348682798861, 76.47802901504163, 10, 10, 0),
    (16, 220.12165780322232, 9.999999999999948, 76.47802901504163, 10, 10, 0),
]
for _k in CAM_KEYS:
    cam.location = (_k[1], _k[2], _k[3])
    cam.keyframe_insert(data_path="location", frame=_k[0])
    cam_target.location = (_k[4], _k[5], _k[6])
    cam_target.keyframe_insert(data_path="location", frame=_k[0])

def _thide_set_interp(idblock, mode):
    _ad = getattr(idblock, "animation_data", None)
    if not _ad or not _ad.action:
        return
    _curves = getattr(_ad.action, "fcurves", None)
    if not _curves:
        try:
            _slot = _ad.action_slot
            _curves = []
            for _layer in _ad.action.layers:
                for _strip in _layer.strips:
                    _bag = _strip.channelbag(_slot)
                    if _bag:
                        _curves = list(_bag.fcurves) + _curves
        except Exception:
            _curves = []
    for _fc in _curves:
        for _kp in _fc.keyframe_points:
            _kp.interpolation = "LINEAR"
_thide_set_interp(cam, "LINEAR")
_thide_set_interp(cam_target, "LINEAR")

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 32
scene.cycles.use_denoising = True
scene.cycles.seed = SEED

scene.cycles.device = 'CPU'
thide("device", "CPU")

# ---- output ----
scene.render.resolution_x = 960
scene.render.resolution_y = 540
scene.render.resolution_percentage = 100
scene.render.fps = 8
scene.frame_start = 1
scene.frame_end = 16
OUT_DIR = "out"
os.makedirs(OUT_DIR, exist_ok=True)
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = "MPEG4"
scene.render.ffmpeg.codec = "H264"
scene.render.ffmpeg.constant_rate_factor = 'HIGH'
scene.render.ffmpeg.audio_codec = 'NONE'
scene.render.filepath = os.path.join(OUT_DIR, "golden-camera.mp4")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 16


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(animation=True)
thide("output", scene.render.filepath)
thide("done", "1")
