# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden orbit video
# Created by: ThIDE golden tests
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "2598c23802373fff7789b670689ef332f558f040b5946c258f5cf43604f10ce4"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


def thide_enum(obj, prop, candidates):
    for candidate in candidates:
        try:
            setattr(obj, prop, candidate)
            return candidate
        except TypeError:
            continue
    return None


def thide_fcurves(idblock):
    _ad = getattr(idblock, "animation_data", None)
    if not _ad or not _ad.action:
        return []
    _curves = getattr(_ad.action, "fcurves", None)
    if _curves:
        return list(_curves)
    _curves = []
    try:
        for _layer in _ad.action.layers:
            for _strip in _layer.strips:
                _bag = _strip.channelbag(_ad.action_slot)
                if _bag:
                    _curves = list(_bag.fcurves) + _curves
    except Exception:
        return []
    return _curves


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.data.batch_remove(list(bpy.data.objects))
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 7

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- material: depthgradient (BA-B7) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_nt = mat.node_tree
_bsdf = next(n for n in _nt.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
_geo = _nt.nodes.new("ShaderNodeNewGeometry")
_sep = _nt.nodes.new("ShaderNodeSeparateXYZ")
_nt.links.new(_geo.outputs["Position"], _sep.inputs["Vector"])
_map = _nt.nodes.new("ShaderNodeMapRange")
_map.inputs["From Min"].default_value = bounds_min.z
_map.inputs["From Max"].default_value = bounds_max.z
_nt.links.new(_sep.outputs["Z"], _map.inputs["Value"])
_ramp = _nt.nodes.new("ShaderNodeValToRGB")
_cr = _ramp.color_ramp
_cr.elements[0].position = 0.0
_cr.elements[0].color = (0.018500220128379697, 0.03560131487502034, 0.13286832155381798, 1.0)
_cr.elements[1].position = 1.0
_cr.elements[1].color = (0.8879231178819663, 0.7454042095403874, 0.43415363617474895, 1.0)
_e = _cr.elements.new(0.25)
_e.color = (0.10702310297826761, 0.1559264637078274, 0.3419144249086609, 1.0)
_e = _cr.elements.new(0.5)
_e.color = (0.39157247774972326, 0.1559264637078274, 0.10224173308810132, 1.0)
_e = _cr.elements.new(0.75)
_e.color = (0.6938717612919899, 0.39157247774972326, 0.14995978981060856, 1.0)
_nt.links.new(_map.outputs["Result"], _ramp.inputs["Fac"])
_nt.links.new(_ramp.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

# ---- camera: static auto-framed (replaced by the BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 28
cam_data.clip_start = max(0.01, bounds_radius / 1000.0)
cam_data.clip_end = max(100.0, bounds_radius * 10.0)
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

# Back the camera off along an iso direction until the bounding sphere fits the FOV.
_padding = 1.25
_distance = (bounds_radius * _padding) / math.tan(cam_data.angle / 2.0) + bounds_radius
_direction = mathutils.Vector((1.0, -1.0, 0.7)).normalized()
cam.location = bounds_center + _direction * _distance
cam.rotation_euler = (bounds_center - cam.location).to_track_quat('-Z', 'Y').to_euler()

# ---- lighting: sunsky (BA-B7) ----
_light_strength = 1
_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0 * _light_strength
_suno = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(_suno)
_suno.rotation_euler = (0.9, 0.2, 0.6)
world = bpy.data.worlds.new("CaveWorld")
scene.world = world
world.use_nodes = True
_wnt = world.node_tree
_bg = next(n for n in _wnt.nodes if n.type == 'BACKGROUND')
_sky = _wnt.nodes.new("ShaderNodeTexSky")
# 4.x names the physical sky NISHITA; 5.x replaced it with the *_SCATTERING models.
thide_enum(_sky, "sky_type", ("NISHITA", "MULTIPLE_SCATTERING", "SINGLE_SCATTERING"))
_wnt.links.new(_sky.outputs["Color"], _bg.inputs["Color"])
_bg.inputs["Strength"].default_value = 0.5 * _light_strength

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 96
scene.cycles.use_denoising = True
scene.cycles.seed = SEED
scene.cycles.max_bounces = 8
scene.cycles.diffuse_bounces = 3
scene.cycles.glossy_bounces = 3
scene.cycles.transmission_bounces = 4
scene.cycles.caustics_reflective = False
scene.cycles.caustics_refractive = False

def _enable_gpu(kind):
    prefs = bpy.context.preferences.addons["cycles"].preferences
    prefs.compute_device_type = kind
    if hasattr(prefs, "refresh_devices"):
        prefs.refresh_devices()
    else:
        prefs.get_devices()
    found = False
    for device in prefs.devices:
        device.use = device.type == kind
        found = found or device.use
    return found

_gpu_cascade = ["OPTIX", "CUDA", "HIP", "ONEAPI", "METAL"]
for _kind in _gpu_cascade:
    try:
        if _enable_gpu(_kind):
            scene.cycles.device = 'GPU'
            thide("device", _kind)
            break
    except Exception:
        continue
else:
    scene.cycles.device = 'CPU'
    thide("device", "CPU")

# ---- interactive preview (opened from ThIDE — build the scene, skip rendering) ----
scene.render.resolution_x = 1280
scene.render.resolution_y = 720
scene.render.resolution_percentage = 100
scene.render.fps = 24
scene.frame_start = 1
scene.frame_end = 120
scene.frame_set(1)

model.select_set(True)
if bpy.context.view_layer is not None:
    bpy.context.view_layer.objects.active = model
try:
    for _win in bpy.context.window_manager.windows:
        for _area in _win.screen.areas:
            if _area.type == 'VIEW_3D':
                _area.spaces.active.region_3d.view_perspective = 'CAMERA'
except Exception:
    pass
thide("phase", "interactive")
