# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden overlays
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "729df23f57cecb5954d45281fb1c77fc89434d52b5a7f0731ef6375c90973ff8"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 9

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- material: depthgradient (BA-B7) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_nt = mat.node_tree
_bsdf = next(n for n in _nt.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
_geo = _nt.nodes.new("ShaderNodeNewGeometry")
_sep = _nt.nodes.new("ShaderNodeSeparateXYZ")
_nt.links.new(_geo.outputs["Position"], _sep.inputs["Vector"])
_map = _nt.nodes.new("ShaderNodeMapRange")
_map.inputs["From Min"].default_value = bounds_min.z
_map.inputs["From Max"].default_value = bounds_max.z
_nt.links.new(_sep.outputs["Z"], _map.inputs["Value"])
_ramp = _nt.nodes.new("ShaderNodeValToRGB")
_cr = _ramp.color_ramp
_cr.elements[0].position = 0.0
_cr.elements[0].color = (0.018500220128379697, 0.03560131487502034, 0.13286832155381798, 1.0)
_cr.elements[1].position = 1.0
_cr.elements[1].color = (0.8879231178819663, 0.7454042095403874, 0.43415363617474895, 1.0)
_e = _cr.elements.new(0.25)
_e.color = (0.10702310297826761, 0.1559264637078274, 0.3419144249086609, 1.0)
_e = _cr.elements.new(0.5)
_e.color = (0.39157247774972326, 0.1559264637078274, 0.10224173308810132, 1.0)
_e = _cr.elements.new(0.75)
_e.color = (0.6938717612919899, 0.39157247774972326, 0.14995978981060856, 1.0)
_nt.links.new(_map.outputs["Result"], _ramp.inputs["Fac"])
_nt.links.new(_ramp.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

# ---- camera: static auto-framed (replaced by the BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 35
cam_data.clip_start = max(0.01, bounds_radius / 1000.0)
cam_data.clip_end = max(100.0, bounds_radius * 10.0)
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

# Back the camera off along an iso direction until the bounding sphere fits the FOV.
_padding = 1.15
_distance = (bounds_radius * _padding) / math.tan(cam_data.angle / 2.0) + bounds_radius
_direction = mathutils.Vector((1.0, -1.0, 0.7)).normalized()
cam.location = bounds_center + _direction * _distance
cam.rotation_euler = (bounds_center - cam.location).to_track_quat('-Z', 'Y').to_euler()

# ---- lighting: sunsky (BA-B7) ----
_light_strength = 1
_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0 * _light_strength
_suno = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(_suno)
_suno.rotation_euler = (0.9, 0.2, 0.6)
world = bpy.data.worlds.new("CaveWorld")
scene.world = world
world.use_nodes = True
_wnt = world.node_tree
_bg = next(n for n in _wnt.nodes if n.type == 'BACKGROUND')
_sky = _wnt.nodes.new("ShaderNodeTexSky")
_sky.sky_type = 'NISHITA'
_wnt.links.new(_sky.outputs["Color"], _bg.inputs["Color"])
_bg.inputs["Strength"].default_value = 0.5 * _light_strength

# ---- labels & annotations (BA-B8) ----
_label_color = (0.95, 0.93, 0.82, 1.0)
_lbl_mat = bpy.data.materials.new("LabelText")
_lbl_mat.use_nodes = True
_lnt = _lbl_mat.node_tree
_lnt.nodes.clear()
_lemit = _lnt.nodes.new("ShaderNodeEmission")
_lemit.inputs["Color"].default_value = _label_color
_lemit.inputs["Strength"].default_value = 1.5
_lout = _lnt.nodes.new("ShaderNodeOutputMaterial")
_lnt.links.new(_lemit.outputs["Emission"], _lout.inputs["Surface"])

def _thide_label(name, body, loc, size, bucket):
    _c = bpy.data.curves.new(name, type='FONT')
    _c.body = body
    _c.size = size
    _c.align_x = 'CENTER'
    _c.align_y = 'CENTER'
    _o = bpy.data.objects.new(name, _c)
    _o.data.materials.append(_lbl_mat)
    _o.location = loc
    scene.collection.objects.link(_o)
    _cst = _o.constraints.new(type='TRACK_TO')
    _cst.target = cam
    _cst.track_axis = 'TRACK_Z'
    _cst.up_axis = 'UP_Y'
    bucket.append(_o)
    return _o

_station_labels = []
_component_labels = []
_lead_markers = []
_overlays = []

STATION_LABELS = [
    ("entrance.main", -50, -30, 25, 1.874459922217597),
    ("entrance.upper", 40, 20, 28, 1.874459922217597),
]
for _i in STATION_LABELS:
    _thide_label("stn:" + _i[0], _i[0], (_i[1], _i[2], _i[3]), _i[4], _station_labels)

_lead_mat = bpy.data.materials.new("LeadMarker")
_lead_mat.use_nodes = True
_dnt = _lead_mat.node_tree
_dnt.nodes.clear()
_demit = _dnt.nodes.new("ShaderNodeEmission")
_demit.inputs["Color"].default_value = (1.0, 0.25, 0.1, 1.0)
_demit.inputs["Strength"].default_value = 2.0
_dout = _dnt.nodes.new("ShaderNodeOutputMaterial")
_dnt.links.new(_demit.outputs["Emission"], _dout.inputs["Surface"])

def _thide_lead(name, loc, radius):
    bpy.ops.mesh.primitive_ico_sphere_add(radius=radius, subdivisions=2, location=loc)
    _o = bpy.context.active_object
    _o.name = name
    _o.data.materials.append(_lead_mat)
    _lead_markers.append(_o)
    return _o

LEAD_MARKERS = [
    ("strong draught", 0, 0, -10, 1.5620499351813308, 1.874459922217597),
    ("sump.3", -20, 10, -25, 1.5620499351813308, 1.874459922217597),
]
for _d in LEAD_MARKERS:
    _dm = _thide_lead("lead:" + _d[0], (_d[1], _d[2], _d[3]), _d[4])
# presentation overlays (camera HUD + world markers)
def _thide_hud(name, body, loc, size):
    _c = bpy.data.curves.new(name, type='FONT')
    _c.body = body
    _c.size = size
    _c.align_x = 'CENTER'
    _c.align_y = 'CENTER'
    _o = bpy.data.objects.new(name, _c)
    _o.data.materials.append(_lbl_mat)
    scene.collection.objects.link(_o)
    _o.parent = cam
    _o.location = loc
    _overlays.append(_o)
    return _o

def _thide_nice(v):
    _base = 10.0 ** math.floor(math.log10(max(v, 1.0)))
    for _f in (1, 2, 5, 10):
        if _f * _base >= v:
            return _f * _base
    return 10.0 * _base

_thide_hud("overlay:title", "Peștera de Aur", (0.0, -1.15, -3.0), 0.16)
_north_r = bounds_radius * 0.05
_north_pos = (bounds_center.x, bounds_max.y + bounds_radius * 0.15, bounds_max.z)
bpy.ops.mesh.primitive_cone_add(radius1=_north_r, depth=_north_r * 3.0, location=_north_pos, rotation=(-math.pi / 2.0, 0.0, 0.0))
_na = bpy.context.active_object
_na.name = "overlay:north"
_na.data.materials.append(_lbl_mat)
_overlays.append(_na)
_thide_label("overlay:north-n", "N", (bounds_center.x, bounds_max.y + bounds_radius * 0.28, bounds_max.z), _north_r * 3.0, _overlays)
_bar_len = _thide_nice(bounds_radius)
bpy.ops.mesh.primitive_cube_add(size=1.0, location=(bounds_center.x, bounds_min.y, bounds_min.z))
_sb = bpy.context.active_object
_sb.name = "overlay:scalebar"
_sb.scale = (_bar_len / 2.0, bounds_radius * 0.01, bounds_radius * 0.01)
_sb.data.materials.append(_lbl_mat)
_overlays.append(_sb)
_thide_label("overlay:scalebar-txt", str(int(_bar_len)) + " m", (bounds_center.x, bounds_min.y, bounds_min.z - bounds_radius * 0.06), bounds_radius * 0.04, _overlays)
_legend = [(0.8879231178819663, 0.7454042095403874, 0.43415363617474895, 1.0), (0.6938717612919899, 0.39157247774972326, 0.14995978981060856, 1.0), (0.39157247774972326, 0.1559264637078274, 0.10224173308810132, 1.0), (0.10702310297826761, 0.1559264637078274, 0.3419144249086609, 1.0), (0.018500220128379697, 0.03560131487502034, 0.13286832155381798, 1.0)]
for _idx, _col in enumerate(_legend):
    _lm = bpy.data.materials.new("LegendStop")
    _lm.use_nodes = True
    _lmt = _lm.node_tree
    _lmt.nodes.clear()
    _le = _lmt.nodes.new("ShaderNodeEmission")
    _le.inputs["Color"].default_value = _col
    _lo = _lmt.nodes.new("ShaderNodeOutputMaterial")
    _lmt.links.new(_le.outputs["Emission"], _lo.inputs["Surface"])
    bpy.ops.mesh.primitive_plane_add(size=1.0)
    _lp = bpy.context.active_object
    _lp.name = "overlay:legend" + str(_idx)
    _lp.data.materials.append(_lm)
    _lp.parent = cam
    _lp.scale = (0.05, 0.05, 0.05)
    _lp.location = (1.15, 0.5 - _idx * 0.13, -3.0)
    _overlays.append(_lp)

# visibility / fade events
def _thide_visibility(objs, show_frame, hide_frame, fade_frames):
    for _o in objs:
        if show_frame is not None:
            _o.hide_render = True
            _o.hide_viewport = True
            _o.keyframe_insert(data_path="hide_render", frame=max(1, show_frame - 1))
            _o.keyframe_insert(data_path="hide_viewport", frame=max(1, show_frame - 1))
            _o.hide_render = False
            _o.hide_viewport = False
            _o.keyframe_insert(data_path="hide_render", frame=show_frame)
            _o.keyframe_insert(data_path="hide_viewport", frame=show_frame)
            if fade_frames > 0:
                _base = tuple(_o.scale)
                _o.scale = (_base[0] * 0.001, _base[1] * 0.001, _base[2] * 0.001)
                _o.keyframe_insert(data_path="scale", frame=show_frame)
                _o.scale = _base
                _o.keyframe_insert(data_path="scale", frame=show_frame + fade_frames)
        if hide_frame is not None:
            _o.hide_render = False
            _o.keyframe_insert(data_path="hide_render", frame=max(1, hide_frame - 1))
            _o.hide_render = True
            _o.hide_viewport = True
            _o.keyframe_insert(data_path="hide_render", frame=hide_frame)
            _o.keyframe_insert(data_path="hide_viewport", frame=hide_frame)

_thide_visibility(_station_labels, 12, None, 12)
_thide_visibility(_lead_markers, None, 36, 0)


# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 32
scene.cycles.use_denoising = True
scene.cycles.seed = SEED
scene.cycles.max_bounces = 8
scene.cycles.diffuse_bounces = 3
scene.cycles.glossy_bounces = 3
scene.cycles.transmission_bounces = 4
scene.cycles.caustics_reflective = False
scene.cycles.caustics_refractive = False

scene.cycles.device = 'CPU'
thide("device", "CPU")

# ---- output ----
scene.render.resolution_x = 960
scene.render.resolution_y = 540
scene.render.resolution_percentage = 100
scene.render.fps = 12
scene.frame_start = 1
scene.frame_end = 48
OUT_DIR = "out"
os.makedirs(OUT_DIR, exist_ok=True)
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = "MPEG4"
scene.render.ffmpeg.codec = "H264"
scene.render.ffmpeg.constant_rate_factor = 'HIGH'
scene.render.ffmpeg.audio_codec = 'NONE'
scene.render.filepath = os.path.join(OUT_DIR, "golden-labels.mp4")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 48


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(animation=True)
thide("output", scene.render.filepath)
thide("done", "1")
