# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden still — Peștera "Test"
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "d7bd34415193a5adb4c608c9182a078ff0c190d305d79f57462b802d8511a18f"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 3

# ---- import model ----
thide("phase", "import")
PLY_PATH = "C:\\caves\\model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- baseline material + light (replaced by the BA-B7 sections) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
if model.data.color_attributes:
    _vc = mat.node_tree.nodes.new("ShaderNodeVertexColor")
    _vc.layer_name = model.data.color_attributes[0].name
    mat.node_tree.links.new(_vc.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0
sun = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(sun)
sun.rotation_euler = (0.9, 0.2, 0.6)

# ---- camera: static auto-framed (replaced by the BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 35
cam_data.clip_start = max(0.01, bounds_radius / 1000.0)
cam_data.clip_end = max(100.0, bounds_radius * 10.0)
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

# Back the camera off along an iso direction until the bounding sphere fits the FOV.
_padding = 1.15
_distance = (bounds_radius * _padding) / math.tan(cam_data.angle / 2.0) + bounds_radius
_direction = mathutils.Vector((1.0, -1.0, 0.7)).normalized()
cam.location = bounds_center + _direction * _distance
cam.rotation_euler = (bounds_center - cam.location).to_track_quat('-Z', 'Y').to_euler()

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = True
for _engine_id in ("BLENDER_EEVEE_NEXT", "BLENDER_EEVEE"):
    try:
        scene.render.engine = _engine_id
        break
    except TypeError:
        continue
else:
    fail("no EEVEE engine is available in this Blender")
scene.eevee.taa_render_samples = 32
thide("device", "EEVEE")

# ---- output ----
scene.render.resolution_x = 801
scene.render.resolution_y = 601
scene.render.resolution_percentage = 100
scene.render.fps = 30
scene.frame_start = 1
scene.frame_end = 1
OUT_DIR = "out/stills"
os.makedirs(OUT_DIR, exist_ok=True)
scene.render.image_settings.file_format = 'PNG'
scene.render.image_settings.color_mode = "RGBA"
scene.render.filepath = os.path.join(OUT_DIR, "golden-still.png")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 1


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(write_still=True)
thide("output", scene.render.filepath)
thide("done", "1")
