# Generated by ThIDE (Therion.Blender) — do not edit; regenerate from the spec.
# Spec: Golden orbit video
# Created by: ThIDE golden tests
# Run: blender -b --factory-startup --python <this file>

import math
import os
import sys

import bpy
import mathutils

SPEC_HASH = "3913912e85275c87dc7b1b8e68a2724bf6793a61a0731ef2d1ca3c7f51be23ec"


def thide(key, value):
    print("THIDE:" + key + "=" + str(value), flush=True)


def fail(message, code=64):
    thide("error", message)
    sys.exit(code)


thide("spec-hash", SPEC_HASH)
thide("blender", ".".join(str(v) for v in bpy.app.version))
if bpy.app.version < (4, 2, 0):
    fail("ThIDE requires Blender 4.2 or newer, found " + bpy.app.version_string)

# ---- scene reset ----
thide("phase", "scene")
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1.0
SEED = 7

# ---- import model ----
thide("phase", "import")
PLY_PATH = "assets/model.ply"
if not os.path.exists(PLY_PATH):
    fail("model file not found: " + PLY_PATH)
bpy.ops.wm.ply_import(filepath=PLY_PATH)
model = bpy.context.selected_objects[0] if bpy.context.selected_objects else None
if model is None:
    fail("PLY import produced no object")
model.name = "CaveModel"
thide("triangles", len(model.data.polygons))

# Runtime bounds of the (already recentered) model drive framing and clipping.
_corners = [model.matrix_world @ mathutils.Vector(c) for c in model.bound_box]
bounds_min = mathutils.Vector((min(c[i] for c in _corners) for i in range(3)))
bounds_max = mathutils.Vector((max(c[i] for c in _corners) for i in range(3)))
bounds_center = (bounds_min + bounds_max) / 2
bounds_radius = max((bounds_max - bounds_min).length / 2, 1.0)

# ---- baseline material + light (replaced by the BA-B7 sections) ----
mat = bpy.data.materials.new("CaveRock")
mat.use_nodes = True
_bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
_bsdf.inputs["Roughness"].default_value = 0.9
if model.data.color_attributes:
    _vc = mat.node_tree.nodes.new("ShaderNodeVertexColor")
    _vc.layer_name = model.data.color_attributes[0].name
    mat.node_tree.links.new(_vc.outputs["Color"], _bsdf.inputs["Base Color"])
model.data.materials.append(mat)

_sun = bpy.data.lights.new("Sun", type='SUN')
_sun.energy = 3.0
sun = bpy.data.objects.new("Sun", _sun)
scene.collection.objects.link(sun)
sun.rotation_euler = (0.9, 0.2, 0.6)

# ---- camera: static auto-framed (replaced by the BA-B6 camera engine) ----
cam_data = bpy.data.cameras.new("Camera")
cam_data.lens = 28
cam_data.clip_start = max(0.01, bounds_radius / 1000.0)
cam_data.clip_end = max(100.0, bounds_radius * 10.0)
cam = bpy.data.objects.new("Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam

# Back the camera off along an iso direction until the bounding sphere fits the FOV.
_padding = 1.25
_distance = (bounds_radius * _padding) / math.tan(cam_data.angle / 2.0) + bounds_radius
_direction = mathutils.Vector((1.0, -1.0, 0.7)).normalized()
cam.location = bounds_center + _direction * _distance
cam.rotation_euler = (bounds_center - cam.location).to_track_quat('-Z', 'Y').to_euler()

# ---- engine ----
thide("phase", "engine")
scene.render.film_transparent = False
scene.render.engine = 'CYCLES'
scene.cycles.samples = 96
scene.cycles.use_denoising = True
scene.cycles.seed = SEED

def _enable_gpu(kind):
    prefs = bpy.context.preferences.addons["cycles"].preferences
    prefs.compute_device_type = kind
    if hasattr(prefs, "refresh_devices"):
        prefs.refresh_devices()
    else:
        prefs.get_devices()
    found = False
    for device in prefs.devices:
        device.use = device.type == kind
        found = found or device.use
    return found

_gpu_cascade = ["OPTIX", "CUDA", "HIP", "ONEAPI", "METAL"]
for _kind in _gpu_cascade:
    try:
        if _enable_gpu(_kind):
            scene.cycles.device = 'GPU'
            thide("device", _kind)
            break
    except Exception:
        continue
else:
    scene.cycles.device = 'CPU'
    thide("device", "CPU")

# ---- output ----
scene.render.resolution_x = 1280
scene.render.resolution_y = 720
scene.render.resolution_percentage = 100
scene.render.fps = 24
scene.frame_start = 1
scene.frame_end = 120
OUT_DIR = "out"
os.makedirs(OUT_DIR, exist_ok=True)
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = "MPEG4"
scene.render.ffmpeg.codec = "H264"
scene.render.ffmpeg.constant_rate_factor = 'HIGH'
scene.render.ffmpeg.audio_codec = 'NONE'
scene.render.filepath = os.path.join(OUT_DIR, "golden-video.mp4")

# ---- progress hooks (THIDE: tier-1 protocol, D-08) ----
FRAME_COUNT = 120


def _thide_frame_written(*args):
    thide("frame", str(bpy.context.scene.frame_current) + "/" + str(FRAME_COUNT))


def _thide_render_cancelled(*args):
    thide("render-cancel", "1")


bpy.app.handlers.render_write.append(_thide_frame_written)
bpy.app.handlers.render_cancel.append(_thide_render_cancelled)

# ---- render ----
thide("phase", "render")
thide("frames", FRAME_COUNT)
bpy.ops.render.render(animation=True)
thide("output", scene.render.filepath)
thide("done", "1")
